import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fitAffineTransform, applyAffineTransform, type AffinePoint } from './affine-fit.js';

// Generated by hand from the known transform a=2, b=0.5, c=1, d=-0.3, e=1.5, f=2.
const THREE_POINTS: AffinePoint[] = [
  { worldX: 0, worldZ: 0, fx: 1, fy: 2 },
  { worldX: 100, worldZ: 0, fx: 201, fy: -28 },
  { worldX: 0, worldZ: 100, fx: 51, fy: 152 },
];

const FOUR_POINTS: AffinePoint[] = [
  ...THREE_POINTS,
  { worldX: 50, worldZ: 50, fx: 126, fy: 62 },
];

function assertRecoversKnownTransform(transform: ReturnType<typeof fitAffineTransform>) {
  assert.ok(Math.abs(transform.a - 2) < 1e-9);
  assert.ok(Math.abs(transform.b - 0.5) < 1e-9);
  assert.ok(Math.abs(transform.c - 1) < 1e-9);
  assert.ok(Math.abs(transform.d - -0.3) < 1e-9);
  assert.ok(Math.abs(transform.e - 1.5) < 1e-9);
  assert.ok(Math.abs(transform.f - 2) < 1e-9);
}

test('fitAffineTransform recovers an exact transform from exactly 3 points', () => {
  assertRecoversKnownTransform(fitAffineTransform(THREE_POINTS));
});

test('fitAffineTransform recovers an exact transform from more than 3 consistent points', () => {
  assertRecoversKnownTransform(fitAffineTransform(FOUR_POINTS));
});

test('fitAffineTransform throws with fewer than 3 points', () => {
  assert.throws(() => fitAffineTransform(THREE_POINTS.slice(0, 2)), /at least 3 points/);
});

test('applyAffineTransform round-trips through a fitted transform', () => {
  const transform = fitAffineTransform(THREE_POINTS);
  const result = applyAffineTransform(transform, 50, 50);
  assert.ok(Math.abs(result.fx - 126) < 1e-9);
  assert.ok(Math.abs(result.fy - 62) < 1e-9);
});
