// Named locations, positioned relative to their region's bounding box
// (fx/fy are 0-1 fractions within the region — see regions.ts). Positions
// are approximate, based on general knowledge of relative in-region
// geography plus a research pass cross-referencing eldenring.wiki.gg
// (explicitly not Fextralife/Fandom) and general gaming-press coverage for
// field-boss siting. V1 scope: naming and rough placement only, nothing
// interactive per-pin yet. A handful of names the research pass flagged as
// low-confidence or likely duplicates (e.g. "Academy Crystal Cave" as a
// distinct dungeon, "Gael Tunnel" as standalone) were left out rather than
// guessed onto the map.
export interface MapLocation {
  name: string;
  category:
    | 'legacy-dungeon'
    | 'minor-dungeon'
    | 'evergaol'
    | 'church'
    | 'landmark'
    | 'town-or-fort'
    | 'great-enemy';
  regionId: string;
  layer: 'surface' | 'underground';
  fx: number;
  fy: number;
}

export const MAP_LOCATIONS: MapLocation[] = [
  // ================= LIMGRAVE =================
  { name: 'Chapel of Anticipation', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.924, fy: 0.565 },
  { name: 'Stranded Graveyard', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.824, fy: 0.565 },
  { name: 'Stormveil Castle', category: 'legacy-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.834, fy: 0.562 },
  { name: 'Stormgate', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.816, fy: 0.575 },
  { name: 'Divine Tower of Limgrave', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.851, fy: 0.568 },
  { name: "Fringefolk Hero's Grave", category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.822, fy: 0.588 },
  { name: 'Stormhill Evergaol', category: 'evergaol', regionId: 'limgrave', layer: 'surface', fx: 0.804, fy: 0.607 },
  { name: 'Stormhill Shack', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.775, fy: 0.588 },
  { name: 'Tree Sentinel (Limgrave)', category: 'great-enemy', regionId: 'limgrave', layer: 'surface', fx: 0.756, fy: 0.598 },
  { name: 'Highroad Cave', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.893, fy: 0.542 },
  { name: 'Deathtouched Catacombs', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.922, fy: 0.607 },
  { name: 'Third Church of Marika', category: 'church', regionId: 'limgrave', layer: 'surface', fx: 0.951, fy: 0.575 },
  { name: 'Tibia Mariner (Limgrave site)', category: 'great-enemy', regionId: 'limgrave', layer: 'surface', fx: 0.951, fy: 0.594 },
  { name: 'Summonwater Village', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 0.981, fy: 0.575 },
  { name: 'Fort Haight', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 1.069, fy: 0.575 },
  { name: 'Church of Elleh', category: 'church', regionId: 'limgrave', layer: 'surface', fx: 0.793, fy: 0.691 },
  { name: "Warmaster's Shack", category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.746, fy: 0.639 },
  { name: 'Stormfoot Catacombs', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.757, fy: 0.671 },
  { name: 'Gatefront Ruins', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 0.834, fy: 0.652 },
  { name: 'Waypoint Ruins', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 0.687, fy: 0.736 },
  { name: 'Coastal Cave', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.707, fy: 0.747 },
  { name: 'Groveside Cave', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.746, fy: 0.781 },
  { name: 'Mistwood Ruins', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 0.951, fy: 0.704 },
  { name: 'Siofra River Well', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.969, fy: 0.717 },
  { name: 'Murkwater Catacombs', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 1.01, fy: 0.736 },
  { name: 'Murkwater Cave', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 1.04, fy: 0.768 },
  { name: 'Church of Dragon Communion', category: 'church', regionId: 'limgrave', layer: 'surface', fx: 0.863, fy: 0.833 },
  { name: 'Agheel Lake', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.863, fy: 0.865 },
  { name: 'Flying Dragon Agheel (site)', category: 'great-enemy', regionId: 'limgrave', layer: 'surface', fx: 0.875, fy: 0.885 },
  { name: 'Dragon-Burnt Ruins', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 0.875, fy: 0.833 },
  { name: 'Forlorn Hound Evergaol', category: 'evergaol', regionId: 'limgrave', layer: 'surface', fx: 0.893, fy: 0.898 },
  { name: 'Bridge of Sacrifice', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 1.04, fy: 0.994 },
  { name: 'Seaside Ruins', category: 'town-or-fort', regionId: 'limgrave', layer: 'surface', fx: 0.756, fy: 0.868 },
  { name: 'Limgrave Tunnels', category: 'minor-dungeon', regionId: 'limgrave', layer: 'surface', fx: 0.834, fy: 0.994 },
  { name: 'Limgrave Colosseum', category: 'landmark', regionId: 'limgrave', layer: 'surface', fx: 0.893, fy: 0.781 },

  // ================= WEEPING PENINSULA =================
  { name: 'Isolated Merchant\'s Shack (Weeping Peninsula)', category: 'landmark', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.176, fy: 0.41 },
  { name: 'Wandering Mausoleum (Weeping Peninsula)', category: 'landmark', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.318, fy: 0.304 },
  { name: 'Weeping Evergaol', category: 'evergaol', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.231, fy: 0.367 },
  { name: 'Church of Pilgrimage', category: 'church', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.289, fy: 0.508 },
  { name: 'Minor Erdtree (Weeping Peninsula)', category: 'landmark', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.23, fy: 0.59 },
  { name: 'Erdtree Avatar (Weeping Peninsula site)', category: 'great-enemy', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.23, fy: 0.614 },
  { name: 'Tombsward Ruins', category: 'town-or-fort', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.318, fy: 0.427 },
  { name: 'Tombsward Cave', category: 'minor-dungeon', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.377, fy: 0.386 },
  { name: 'Tombsward Catacombs', category: 'minor-dungeon', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.347, fy: 0.468 },
  { name: 'Oridys\'s Rise', category: 'landmark', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.259, fy: 0.671 },
  { name: 'Forest Lookout Tower', category: 'landmark', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.201, fy: 0.508 },
  { name: 'Demi-Human Forest Ruins', category: 'town-or-fort', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.142, fy: 0.631 },
  { name: 'Earthbore Cave', category: 'minor-dungeon', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.113, fy: 0.549 },
  { name: 'Ailing Village', category: 'town-or-fort', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.377, fy: 0.468 },
  { name: 'Fourth Church of Marika', category: 'church', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.377, fy: 0.631 },
  { name: 'Tower of Return', category: 'landmark', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.464, fy: 0.549 },
  { name: 'Witchbane Ruins', category: 'town-or-fort', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.464, fy: 0.671 },
  { name: 'Impaler\'s Catacombs', category: 'minor-dungeon', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.435, fy: 0.753 },
  { name: 'Callu Baptismal Church', category: 'church', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.318, fy: 0.793 },
  { name: 'Morne Tunnel', category: 'minor-dungeon', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.178, fy: 0.697 },
  { name: 'Castle Morne', category: 'legacy-dungeon', regionId: 'weeping-peninsula', layer: 'surface', fx: 1.283, fy: 0.824 },

  // ================= LIURNIA OF THE LAKES =================
  { name: 'Rose Church', category: 'church', regionId: 'liurnia', layer: 'surface', fx: 0.396, fy: 0.255 },
  { name: 'Temple Quarter', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.398, fy: 0.195 },
  { name: 'Kingsrealm Ruins', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.373, fy: 0.28 },
  { name: 'Church of Irith', category: 'church', regionId: 'liurnia', layer: 'surface', fx: 0.295, fy: 0.231 },
  { name: 'Three Sisters', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.134, fy: 0.293 },
  { name: "Ranni's Rise", category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.123, fy: 0.268 },
  { name: 'Caria Manor', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.123, fy: 0.377 },
  { name: 'Royal Grave Evergaol', category: 'evergaol', regionId: 'liurnia', layer: 'surface', fx: 0.158, fy: 0.322 },
  { name: 'Ravine-Veiled Village', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.509, fy: 0.462 },
  { name: 'Frenzied Flame Village', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.523, fy: 0.485 },
  { name: 'Cliffbottom Catacombs', category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.523, fy: 0.485 },
  { name: 'Purified Ruins', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.502, fy: 0.504 },
  { name: 'Laskyar Ruins', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.536, fy: 0.413 },
  { name: 'Divine Tower of Liurnia', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.523, fy: 0.485 },
  { name: 'Grand Lift of Dectus', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.518, fy: 0.477 },
  { name: 'Ruin-Strewn Precipice', category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.075, fy: 0.685 },
  { name: 'Magma Wyrm Makar (site)', category: 'great-enemy', regionId: 'liurnia', layer: 'surface', fx: 0.075, fy: 0.739 },
  { name: 'Bellum Church', category: 'church', regionId: 'liurnia', layer: 'surface', fx: 0.103, fy: 0.812 },
  { name: 'Glintstone Dragon Smarag (site)', category: 'great-enemy', regionId: 'liurnia', layer: 'surface', fx: 0.213, fy: 0.63 },
  { name: 'Raya Lucaria Academy', category: 'legacy-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.261, fy: 0.685 },
  { name: 'Academy Gate Town', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.261, fy: 0.776 },
  { name: 'Raya Lucaria Crystal Tunnel', category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.213, fy: 0.812 },
  { name: 'Church of Vows', category: 'church', regionId: 'liurnia', layer: 'surface', fx: 0.33, fy: 0.594 },
  { name: 'The Four Belfries', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.33, fy: 0.921 },
  { name: "Cuckoo's Evergaol", category: 'evergaol', regionId: 'liurnia', layer: 'surface', fx: 0.35, fy: 1.048 },
  { name: 'Highway Lookout Tower (Liurnia)', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.433, fy: 0.413 },
  { name: 'Church of Inhibition', category: 'church', regionId: 'liurnia', layer: 'surface', fx: 0.51, fy: 0.692 },
  { name: "Road's End Catacombs", category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.519, fy: 0.888 },
  { name: 'Ainsel River Well', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.573, fy: 0.968 },
  { name: 'Bellum Highway', category: 'landmark', regionId: 'liurnia', layer: 'surface', fx: 0.467, fy: 1.138 },
  { name: 'Stillwater Cave', category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.359, fy: 1.475 },
  { name: 'Village of the Albinaurics', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.295, fy: 1.501 },
  { name: 'Jarburg', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.269, fy: 1.485 },
  { name: 'Black Knife Catacombs', category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.123, fy: 1.501 },
  { name: "Malefactor's Evergaol", category: 'evergaol', regionId: 'liurnia', layer: 'surface', fx: 0.398, fy: 1.229 },
  { name: "Ringleader's Evergaol", category: 'evergaol', regionId: 'liurnia', layer: 'surface', fx: 0.118, fy: 1.501 },
  { name: 'Cathedral of Manus Celes', category: 'church', regionId: 'liurnia', layer: 'surface', fx: 0.123, fy: 1.411 },
  { name: 'Glintstone Dragon Adula (site)', category: 'great-enemy', regionId: 'liurnia', layer: 'surface', fx: 0.13, fy: 1.356 },
  { name: 'Moonfolk Ruins', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.103, fy: 1.32 },
  { name: 'Lunar Estate Ruins', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.089, fy: 1.229 },
  { name: 'Uld Palace Ruins', category: 'town-or-fort', regionId: 'liurnia', layer: 'surface', fx: 0.144, fy: 1.284 },
  { name: 'Lakeside Crystal Cave', category: 'minor-dungeon', regionId: 'liurnia', layer: 'surface', fx: 0.109, fy: 0.449 },

  // ================= CAELID =================
  { name: 'Fort Faroth', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.235, fy: 1.261 },
  { name: 'Elder Dragon Greyoll (site)', category: 'great-enemy', regionId: 'caelid', layer: 'surface', fx: 0.217, fy: 1.24 },
  { name: 'Flying Dragon Greyoll (post-quest site)', category: 'great-enemy', regionId: 'caelid', layer: 'surface', fx: 0.325, fy: 1.256 },
  { name: 'Bestial Sanctum', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.392, fy: 1.294 },
  { name: 'Cathedral of Dragon Communion', category: 'church', regionId: 'caelid', layer: 'surface', fx: 0.579, fy: 1.163 },
  { name: 'Caelem Ruins', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.614, fy: 1.231 },
  { name: "Lenne's Rise", category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.565, fy: 1.35 },
  { name: 'Dragonbarrow Cave', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.625, fy: 1.177 },
  { name: 'Deep Siofra Well', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.381, fy: 1.294 },
  { name: 'Minor Erdtree Catacombs', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.217, fy: 1.312 },
  { name: 'Abandoned Cave', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.299, fy: 1.357 },
  { name: 'Caelid Catacombs', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.258, fy: 1.402 },
  { name: 'Caelid Waypoint Ruins', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.462, fy: 1.402 },
  { name: 'Smoldering Church', category: 'church', regionId: 'caelid', layer: 'surface', fx: 0.503, fy: 1.447 },
  { name: 'Caelid Colosseum', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.544, fy: 1.402 },
  { name: 'Decaying Ekzykes (site)', category: 'great-enemy', regionId: 'caelid', layer: 'surface', fx: 0.503, fy: 1.492 },
  { name: 'Forsaken Ruins', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.386, fy: 1.291 },
  { name: 'Redmane Castle', category: 'legacy-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.34, fy: 1.536 },
  { name: 'Wailing Dunes', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.299, fy: 1.581 },
  { name: 'Caelid Evergaol (Sellia)', category: 'evergaol', regionId: 'caelid', layer: 'surface', fx: 0.217, fy: 1.536 },
  { name: 'Gaol Cave', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.217, fy: 1.492 },
  { name: 'Fort Gael', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.236, fy: 1.603 },
  { name: 'Sellia Crystal Tunnel', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.244, fy: 1.621 },
  { name: 'Sellia Hideaway', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.263, fy: 1.664 },
  { name: 'Sellia Gateway', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.258, fy: 1.671 },
  { name: 'Sellia, Town of Sorcery', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.277, fy: 1.693 },
  { name: "Gowry's Shack", category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.34, fy: 1.761 },
  { name: 'Church of the Plague', category: 'church', regionId: 'caelid', layer: 'surface', fx: 0.381, fy: 1.761 },
  { name: 'Swamp Lookout Tower', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.421, fy: 1.716 },
  { name: 'Street of Sages Ruins', category: 'town-or-fort', regionId: 'caelid', layer: 'surface', fx: 0.421, fy: 1.626 },
  { name: 'War-Dead Catacombs', category: 'minor-dungeon', regionId: 'caelid', layer: 'surface', fx: 0.666, fy: 1.581 },
  { name: 'Shack of the Rotting', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.544, fy: 1.581 },
  { name: 'Divine Tower of Caelid', category: 'landmark', regionId: 'caelid', layer: 'surface', fx: 0.579, fy: 1.341 },

  // ================= ALTUS PLATEAU / MT. GELMIR =================
  { name: 'Grand Lift of Dectus (Altus side)', category: 'landmark', regionId: 'altus-plateau', layer: 'surface', fx: 0.267, fy: 0.952 },
  { name: 'Divine Tower of East Altus', category: 'landmark', regionId: 'altus-plateau', layer: 'surface', fx: 0.226, fy: 0.979 },
  { name: 'Shaded Castle', category: 'legacy-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.452, fy: 0.646 },
  { name: 'Second Church of Marika', category: 'church', regionId: 'altus-plateau', layer: 'surface', fx: 0.415, fy: 0.923 },
  { name: 'Mirage Rise', category: 'landmark', regionId: 'altus-plateau', layer: 'surface', fx: 0.339, fy: 0.868 },
  { name: 'Old Altus Tunnel', category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.377, fy: 0.979 },
  { name: 'Wyndham Ruins', category: 'town-or-fort', regionId: 'altus-plateau', layer: 'surface', fx: 0.49, fy: 0.979 },
  { name: 'Wyndham Catacombs', category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.528, fy: 1.035 },
  { name: 'Minor Erdtree (Altus Plateau)', category: 'landmark', regionId: 'altus-plateau', layer: 'surface', fx: 0.49, fy: 1.09 },
  { name: 'Minor Erdtree Church', category: 'church', regionId: 'altus-plateau', layer: 'surface', fx: 0.505, fy: 1.112 },
  { name: 'Woodfolk Ruins', category: 'town-or-fort', regionId: 'altus-plateau', layer: 'surface', fx: 0.565, fy: 0.979 },
  { name: 'Golden Lineage Evergaol', category: 'evergaol', regionId: 'altus-plateau', layer: 'surface', fx: 0.565, fy: 0.923 },
  { name: 'Fallingstar Beast (site)', category: 'great-enemy', regionId: 'altus-plateau', layer: 'surface', fx: 0.678, fy: 0.868 },
  { name: 'Erdtree-Gazing Hill', category: 'landmark', regionId: 'altus-plateau', layer: 'surface', fx: 0.678, fy: 0.846 },
  { name: "Sainted Hero's Grave", category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.701, fy: 0.89 },
  { name: 'Lux Ruins', category: 'town-or-fort', regionId: 'altus-plateau', layer: 'surface', fx: 0.754, fy: 1.035 },
  { name: 'Auriza Side Tomb', category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.678, fy: 1.111 },
  { name: "Auriza Hero's Grave", category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.68, fy: 1.107 },
  { name: "Giant-Conquering Hero's Grave (Altus side)", category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.603, fy: 0.591 },
  { name: 'Sealed Tunnel', category: 'minor-dungeon', regionId: 'altus-plateau', layer: 'surface', fx: 0.415, fy: 0.757 },
  { name: 'Volcano Manor', category: 'legacy-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 1.075, fy: 0.753 },
  { name: 'Fort Laiedd', category: 'town-or-fort', regionId: 'mt-gelmir', layer: 'surface', fx: 1.111, fy: 0.9 },
  { name: 'Stormcaller Church', category: 'church', regionId: 'mt-gelmir', layer: 'surface', fx: 1.002, fy: 0.826 },
  { name: 'Ninth Mt. Gelmir Campsite', category: 'landmark', regionId: 'mt-gelmir', layer: 'surface', fx: 1.147, fy: 0.826 },
  { name: 'Magma Wyrm (site)', category: 'great-enemy', regionId: 'mt-gelmir', layer: 'surface', fx: 1.162, fy: 0.812 },
  { name: 'Seethewater Terminus', category: 'landmark', regionId: 'mt-gelmir', layer: 'surface', fx: 1.075, fy: 0.863 },
  { name: 'Seethewater Cave', category: 'minor-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 1.038, fy: 0.885 },
  { name: 'Perfumer\'s Grotto', category: 'minor-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 0.929, fy: 0.68 },
  { name: 'Perfumer\'s Ruins', category: 'town-or-fort', regionId: 'mt-gelmir', layer: 'surface', fx: 0.914, fy: 0.643 },
  { name: "Sage's Cave", category: 'minor-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 0.856, fy: 0.716 },
  { name: 'Hermit Village', category: 'town-or-fort', regionId: 'mt-gelmir', layer: 'surface', fx: 0.819, fy: 0.606 },
  { name: 'Writheblood Ruins', category: 'town-or-fort', regionId: 'mt-gelmir', layer: 'surface', fx: 0.856, fy: 0.533 },
  { name: 'Subterranean Inquisition Chamber', category: 'minor-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 1.038, fy: 0.716 },
  { name: 'Gelmir Hero\'s Grave', category: 'minor-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 0.866, fy: 0.568 },
  { name: 'Altus Tunnel', category: 'minor-dungeon', regionId: 'mt-gelmir', layer: 'surface', fx: 0.965, fy: 0.496 },
  { name: 'Dominula, Windmill Village', category: 'town-or-fort', regionId: 'mt-gelmir', layer: 'surface', fx: 0.884, fy: 0.525 },
  { name: 'Godskin Apostle (Dominula site)', category: 'great-enemy', regionId: 'mt-gelmir', layer: 'surface', fx: 0.889, fy: 0.511 },
  { name: 'West Windmill Pasture', category: 'landmark', regionId: 'mt-gelmir', layer: 'surface', fx: 0.886, fy: 0.519 },
  { name: 'East Windmill Pasture', category: 'landmark', regionId: 'mt-gelmir', layer: 'surface', fx: 0.901, fy: 0.482 },

  // ================= LEYNDELL, ROYAL CAPITAL =================
  { name: 'Draconic Tree Sentinel (site)', category: 'great-enemy', regionId: 'leyndell', layer: 'surface', fx: 0.882, fy: 0.884 },
  { name: 'West Capital Rampart', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.571, fy: 1.277 },
  { name: 'East Capital Rampart', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 1.29, fy: 1.154 },
  { name: 'Fortified Manor', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.56, fy: 1.44 },
  { name: 'Lower Capital Church', category: 'church', regionId: 'leyndell', layer: 'surface', fx: 0.986, fy: 1.511 },
  { name: 'Avenue Balcony', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.864, fy: 1.297 },
  { name: 'Divine Bridge', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.864, fy: 1.582 },
  { name: 'Royal Colosseum', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 1.168, fy: 1.44 },
  { name: 'Erdtree Sanctuary', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.925, fy: 1.011 },
  { name: "Queen's Bedchamber", category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.986, fy: 0.94 },
  { name: 'Elden Throne', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.925, fy: 1.939 },
  { name: 'Subterranean Shunning-Grounds', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.742, fy: 2.01 },
  { name: 'Leyndell Catacombs', category: 'minor-dungeon', regionId: 'leyndell', layer: 'surface', fx: 0.712, fy: 1.973 },
  { name: 'Cathedral of the Forsaken', category: 'landmark', regionId: 'leyndell', layer: 'surface', fx: 0.668, fy: 1.958 },

  // ================= MOUNTAINTOPS OF THE GIANTS / CONSECRATED SNOWFIELD =================
  { name: 'Grand Lift of Rold', category: 'landmark', regionId: 'mountaintops', layer: 'surface', fx: 0.643, fy: 0.581 },
  { name: 'Forbidden Lands', category: 'landmark', regionId: 'mountaintops', layer: 'surface', fx: 0.669, fy: 0.533 },
  { name: 'First Church of Marika', category: 'church', regionId: 'mountaintops', layer: 'surface', fx: 0.669, fy: 0.794 },
  { name: 'Stargazer\'s Ruins', category: 'town-or-fort', regionId: 'mountaintops', layer: 'surface', fx: 0.632, fy: 0.925 },
  { name: "Giant-Conquering Hero's Grave", category: 'minor-dungeon', regionId: 'mountaintops', layer: 'surface', fx: 0.707, fy: 1.187 },
  { name: 'Giants\' Mountaintop Catacombs', category: 'minor-dungeon', regionId: 'mountaintops', layer: 'surface', fx: 0.632, fy: 1.056 },
  { name: 'Zamor Ruins', category: 'town-or-fort', regionId: 'mountaintops', layer: 'surface', fx: 0.569, fy: 1.173 },
  { name: 'Borealis the Freezing Fog (site)', category: 'great-enemy', regionId: 'mountaintops', layer: 'surface', fx: 0.577, fy: 1.157 },
  { name: 'Full-Grown Fallingstar Beast (site)', category: 'great-enemy', regionId: 'mountaintops', layer: 'surface', fx: 0.744, fy: 0.598 },
  { name: 'Guardians\' Garrison', category: 'town-or-fort', regionId: 'mountaintops', layer: 'surface', fx: 0.855, fy: 0.86 },
  { name: 'Church of the Eclipse', category: 'church', regionId: 'mountaintops', layer: 'surface', fx: 0.892, fy: 0.729 },
  { name: 'Castle Sol', category: 'legacy-dungeon', regionId: 'mountaintops', layer: 'surface', fx: 0.855, fy: 0.598 },
  { name: 'Church of Repose', category: 'church', regionId: 'mountaintops', layer: 'surface', fx: 0.521, fy: 1.318 },
  { name: 'Flame Peak', category: 'landmark', regionId: 'mountaintops', layer: 'surface', fx: 0.558, fy: 1.514 },
  { name: 'Forge of the Giants', category: 'landmark', regionId: 'mountaintops', layer: 'surface', fx: 0.595, fy: 1.579 },
  { name: 'Fire Giant (site)', category: 'great-enemy', regionId: 'mountaintops', layer: 'surface', fx: 0.595, fy: 1.605 },
  { name: 'Heretical Rise', category: 'landmark', regionId: 'mountaintops', layer: 'surface', fx: 0.744, fy: 1.448 },
  { name: 'Lord Contender\'s Evergaol', category: 'evergaol', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.411, fy: 2.111 },
  { name: 'Great Wyrm Theodorix (site)', category: 'great-enemy', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.535, fy: 1.986 },
  { name: 'Consecrated Snowfield Catacombs', category: 'minor-dungeon', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.38, fy: 2.236 },
  { name: 'Yelough Anix Tunnel', category: 'minor-dungeon', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.226, fy: 2.111 },
  { name: 'Yelough Anix Ruins', category: 'town-or-fort', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.214, fy: 2.049 },
  { name: 'Cave of the Forlorn', category: 'minor-dungeon', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.288, fy: 2.298 },
  { name: 'Spiritcaller Cave', category: 'minor-dungeon', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.164, fy: 2.236 },
  { name: 'Albinauric Rise', category: 'landmark', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.134, fy: 2.111 },
  { name: 'Apostate Derelict', category: 'town-or-fort', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.154, fy: 2.253 },
  { name: 'Hidden Path to the Haligtree', category: 'landmark', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.169, fy: 2.271 },
  { name: 'Ordina, Liturgical Town', category: 'town-or-fort', regionId: 'consecrated-snowfield', layer: 'surface', fx: 0.349, fy: 2.548 },

  // ================= HALIGTREE =================
  // Previously missing from this dataset entirely — added after the user
  // flagged the omission. Malenia's arena is inside Elphael (a legacy
  // dungeon boss, not open-world), so it isn't pinned separately yet —
  // same "dungeon-interior bosses" gap noted for the Bosses filter above.
  { name: 'Elphael, Brace of the Haligtree', category: 'legacy-dungeon', regionId: 'haligtree', layer: 'surface', fx: 1.908, fy: 0.707 },
  { name: 'Haligtree Town', category: 'town-or-fort', regionId: 'haligtree', layer: 'surface', fx: 1.808, fy: 0.59 },
  { name: 'Haligtree Roots', category: 'landmark', regionId: 'haligtree', layer: 'surface', fx: 1.968, fy: 0.836 },
  { name: 'Prayer Room', category: 'landmark', regionId: 'haligtree', layer: 'surface', fx: 1.898, fy: 0.912 },

  // ================= CRUMBLING FARUM AZULA =================
  { name: 'Crumbling Beast Grave', category: 'landmark', regionId: 'farum-azula', layer: 'surface', fx: 0.884, fy: 2.389 },
  { name: 'Tempest-Facing Balcony', category: 'landmark', regionId: 'farum-azula', layer: 'surface', fx: 0.912, fy: 2.39 },
  { name: 'Dragon Temple', category: 'landmark', regionId: 'farum-azula', layer: 'surface', fx: 1.012, fy: 2.457 },
  { name: 'Dragon Temple Rooftop', category: 'landmark', regionId: 'farum-azula', layer: 'surface', fx: 1.062, fy: 2.39 },
  { name: 'Beside the Great Bridge', category: 'landmark', regionId: 'farum-azula', layer: 'surface', fx: 1.112, fy: 2.524 },
  { name: "Dragonlord Placidusax's Arena", category: 'great-enemy', regionId: 'farum-azula', layer: 'surface', fx: 0.837, fy: 2.591 },

  // ================= UNDERGROUND: SIOFRA RIVER =================
  { name: 'Nokron, Eternal City', category: 'legacy-dungeon', regionId: 'nokron', layer: 'underground', fx: 0.5, fy: 0.4 },
  { name: 'Ancestral Woods', category: 'landmark', regionId: 'nokron', layer: 'underground', fx: 0.3, fy: 0.6 },
  { name: "Night's Sacred Ground", category: 'landmark', regionId: 'nokron', layer: 'underground', fx: 0.4, fy: 0.7 },
  { name: 'Mimic Tear (site)', category: 'great-enemy', regionId: 'nokron', layer: 'underground', fx: 0.42, fy: 0.72 },
  { name: 'Siofra River Well (descent)', category: 'landmark', regionId: 'siofra-river', layer: 'underground', fx: 0.2, fy: 0.15 },
  { name: 'Deep Siofra Well (descent)', category: 'landmark', regionId: 'siofra-river', layer: 'underground', fx: 0.8, fy: 0.15 },
  { name: 'Hallowhorn Grounds (South)', category: 'landmark', regionId: 'siofra-river', layer: 'underground', fx: 0.4, fy: 0.5 },
  { name: 'Hallowhorn Grounds (North)', category: 'landmark', regionId: 'siofra-river', layer: 'underground', fx: 0.45, fy: 0.3 },
  { name: 'Regal Ancestor Spirit (site)', category: 'great-enemy', regionId: 'siofra-river', layer: 'underground', fx: 0.46, fy: 0.28 },
  { name: 'Siofra Aqueduct', category: 'landmark', regionId: 'siofra-river', layer: 'underground', fx: 0.6, fy: 0.4 },
  { name: 'Valiant Gargoyles (site)', category: 'great-enemy', regionId: 'siofra-river', layer: 'underground', fx: 0.62, fy: 0.42 },

  // ================= UNDERGROUND: AINSEL RIVER / NOKSTELLA =================
  { name: 'Ainsel River Well (descent)', category: 'landmark', regionId: 'ainsel-river', layer: 'underground', fx: 0.15, fy: 0.2 },
  { name: 'Ainsel River Main', category: 'landmark', regionId: 'ainsel-river', layer: 'underground', fx: 0.4, fy: 0.4 },
  { name: 'Uhl Palace Ruins', category: 'town-or-fort', regionId: 'ainsel-river', layer: 'underground', fx: 0.7, fy: 0.35 },
  { name: 'Nokstella, Eternal City', category: 'legacy-dungeon', regionId: 'nokstella', layer: 'underground', fx: 0.5, fy: 0.5 },
  { name: 'Renna\'s Rise (waygate)', category: 'landmark', regionId: 'nokstella', layer: 'underground', fx: 0.3, fy: 0.3 },
  { name: 'Moonlight Altar', category: 'landmark', regionId: 'ainsel-river', layer: 'underground', fx: 0.85, fy: 0.55 },

  // ================= UNDERGROUND: LAKE OF ROT =================
  { name: 'Grand Cloister', category: 'landmark', regionId: 'lake-of-rot', layer: 'underground', fx: 0.4, fy: 0.4 },
  { name: 'Astel, Naturalborn of the Void (lair)', category: 'great-enemy', regionId: 'lake-of-rot', layer: 'underground', fx: 0.6, fy: 0.6 },

  // ================= UNDERGROUND: DEEPROOT DEPTHS =================
  { name: 'The Nameless Eternal City', category: 'landmark', regionId: 'deeproot-depths', layer: 'underground', fx: 0.3, fy: 0.5 },
  { name: 'Wandering Mausoleum (Deeproot)', category: 'landmark', regionId: 'deeproot-depths', layer: 'underground', fx: 0.2, fy: 0.25 },
  { name: "Prince of Death's Throne", category: 'landmark', regionId: 'deeproot-depths', layer: 'underground', fx: 0.5, fy: 0.15 },
  { name: 'Lichdragon Fortissax (site)', category: 'great-enemy', regionId: 'deeproot-depths', layer: 'underground', fx: 0.5, fy: 0.13 },

  // ================= UNDERGROUND: MOHGWYN PALACE =================
  { name: 'Mohgwyn Palace', category: 'legacy-dungeon', regionId: 'mohgwyn-palace', layer: 'underground', fx: 0.55, fy: 0.45 },
  { name: 'Dynasty Mausoleum', category: 'landmark', regionId: 'mohgwyn-palace', layer: 'underground', fx: 0.25, fy: 0.4 },
];
